<?php

use App\Jobs\ProcessUserSubmissionJob;
use App\Mail\SimpleEmail;
use App\Models\EmployeeCV;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

uses(RefreshDatabase::class);

beforeEach(function () {
    $this->artisan('db:seed --class=PositionsSeeder');
    $this->artisan('db:seed --class=SalaryLaddersSeeder');
    Mail::fake();
    Storage::fake('public');
    Log::shouldReceive('channel->info')->andReturnNull();
    Log::shouldReceive('channel->error')->andReturnNull();
    Log::shouldReceive('channel->warning')->andReturnNull();
    Log::shouldReceive('info')->andReturnNull();
    Log::shouldReceive('error')->andReturnNull();
    Log::shouldReceive('warning')->andReturnNull();
});

test('job processes application and sends email', function () {
    // Create test data
    $employeeCV = EmployeeCV::factory()->create([
        'personal_info' => [
            'name' => 'Test User',
            'email' => 'test@example.com',
            'mobile' => '12345678',
            'address' => 'Test Address',
            'postal_code' => '1234',
            'postal_place' => 'Test Place',
            'bank_account' => '12345678901',
            'position_size' => '100',
            'employer_and_place' => 'Test Employer',
            'manager_name' => 'Test Manager',
            'manager_mobile' => '12345678',
            'manager_email' => 'manager@example.com',
            'congregation_name' => 'Test Congregation',
            'congregation_mobile' => '12345678',
            'congregation_email' => 'congregation@example.com',
            'birth_date' => '1990-01-01',
        ],
    ]);

    // Mock the data that would be generated by ExcelGenerationService
    $mockData = [
        'application' => $employeeCV,
        'data' => [
            'salaryPlacement' => 50000,
        ],
    ];

    // Execute job
    $job = new ProcessUserSubmissionJob($employeeCV->id, $mockData);
    $job->handle();

    // Assert email was sent
    Mail::assertQueued(SimpleEmail::class, function ($mail) {
        return $mail->hasTo('test@example.com');
    });
});
